from langgraph.graph import StateGraph, END
from langgraph.checkpoint.memory import MemorySaver
from langchain_ollama import ChatOllama
from langchain_core.messages import HumanMessage, SystemMessage
from typing import TypedDict, Optional
import json

from database import run_query
from rag import search_documents
from confidence import calculate_confidence, should_trigger_human_checkpoint

# ─────────────────────────────────────────────
# 1. THE STATE — shared memory across all nodes
# ─────────────────────────────────────────────
# Think of this as a whiteboard every agent can
# read from and write to during one conversation turn.

class AgentState(TypedDict):
    question          : str               # original user question
    route             : Optional[str]     # "sql", "rag", or "both"
    sql_query         : Optional[str]     # SQL generated by LLM
    sql_result        : Optional[dict]    # results from database
    rag_result        : Optional[dict]    # results from ChromaDB
    confidence        : Optional[dict]    # confidence score dict
    checkpoint        : Optional[dict]    # human-in-the-loop info
    awaiting_human    : Optional[bool]    # True if paused for human
    human_decision    : Optional[str]     # "proceed" or "refine"
    final_answer      : Optional[str]     # the clean final answer
    follow_ups        : Optional[list]    # suggested follow-up questions

# ─────────────────────────────────────────────
# 2. THE LLM — using Ollama + Mistral locally
# ─────────────────────────────────────────────
llm = ChatOllama(model="mistral", temperature=0)
# temperature=0 means deterministic — same question always same answer
# good for SQL generation where we want consistency

# ─────────────────────────────────────────────
# 3. NODE 1 — ROUTER
# Reads the question, decides which path to take
# ─────────────────────────────────────────────
def router_node(state: AgentState) -> AgentState:
    print(f"\n🔀 ROUTER: Analyzing question...")

    question = state["question"]

    # Ask the LLM to classify the question
    # We give it 3 choices only — keeps it simple and reliable
    prompt = f"""
You are a routing assistant for a railcar company's AI system.

Classify this question into EXACTLY one of these three categories:
- "sql"  → question needs numbers, counts, or data from the database
- "rag"  → question needs policy rules, guidelines, or documents
- "both" → question needs both data AND policy knowledge

Question: {question}

Reply with ONLY one word: sql, rag, or both.
No explanation. No punctuation. Just the single word.
"""
    response = llm.invoke([HumanMessage(content=prompt)])
    route = response.content.strip().lower()

    # Fallback — if LLM returns something unexpected, default to both
    if route not in ["sql", "rag", "both"]:
        route = "both"

    print(f"   → Route decided: {route}")
    return {**state, "route": route}

# ─────────────────────────────────────────────
# 4. NODE 2 — SQL AGENT
# Generates SQL from plain English, runs it safely
# ─────────────────────────────────────────────
def sql_agent_node(state: AgentState) -> AgentState:
    print(f"\n📊 SQL AGENT: Generating query...")

    question = state["question"]

    # Give LLM the database schema so it knows what tables exist
    schema_prompt = f"""
You are a SQL expert for TrinityRail, a railcar company.

Database tables:

Table: railcars
- car_id (integer) — unique ID for each railcar
- car_type (text) — 'tank', 'boxcar', 'flatcar'
- status (text) — 'idle', 'leased', 'maintenance'
- region (text) — 'north', 'south', 'east', 'west'
- last_inspection_date (text) — format YYYY-MM-DD
- commodity (text) — 'grain', 'chemicals', 'coal', 'none'

Table: leases
- lease_id (integer)
- car_id (integer) — links to railcars
- customer_name (text)
- start_date (text) — format YYYY-MM-DD
- end_date (text) — format YYYY-MM-DD
- monthly_rate (real)

Rules:
- Write ONLY a SELECT query
- No markdown, no explanation, no backticks
- Use date('now') for today's date in SQLite
- Use date('now', '-90 days') for 90 days ago

Question: {question}

SQL query:
"""
    response = llm.invoke([HumanMessage(content=schema_prompt)])
    sql_query = response.content.strip()

    # Remove any markdown backticks if LLM added them anyway
    sql_query = sql_query.replace("```sql", "").replace("```", "").strip()

    print(f"   → Generated SQL: {sql_query}")

    # Run the query safely
    sql_result = run_query(sql_query)
    print(f"   → Rows returned: {sql_result.get('row_count', 0)}")

    return {**state, "sql_query": sql_query, "sql_result": sql_result}

# ─────────────────────────────────────────────
# 5. NODE 3 — RAG AGENT
# Searches ChromaDB for relevant policy documents
# ─────────────────────────────────────────────
def rag_agent_node(state: AgentState) -> AgentState:
    print(f"\n📄 RAG AGENT: Searching policy documents...")

    question = state["question"]
    rag_result = search_documents(question, top_k=3, threshold=0.7)

    print(f"   → Documents found: {rag_result['count']}")
    if rag_result["count"] > 0:
        print(f"   → Best match score: {rag_result['best_score']}")

    return {**state, "rag_result": rag_result}

# ─────────────────────────────────────────────
# 6. NODE 4 — CONFIDENCE CHECKER
# Scores the results, decides if human checkpoint needed
# ─────────────────────────────────────────────
def confidence_node(state: AgentState) -> AgentState:
    print(f"\n🎯 CONFIDENCE: Scoring results...")

    confidence = calculate_confidence(
        sql_result=state.get("sql_result"),
        rag_result=state.get("rag_result"),
        question=state["question"]
    )

    checkpoint = should_trigger_human_checkpoint(
        sql_result=state.get("sql_result"),
        confidence=confidence,
        question=state["question"]
    )

    print(f"   → Confidence: {confidence['level']} ({confidence['score']}/100)")
    print(f"   → Human checkpoint needed: {checkpoint['trigger']}")

    return {
        **state,
        "confidence": confidence,
        "checkpoint": checkpoint,
        "awaiting_human": checkpoint["trigger"]
    }

# ─────────────────────────────────────────────
# 7. NODE 5 — HUMAN CHECKPOINT
# Pauses and waits for user decision
# ─────────────────────────────────────────────
def human_checkpoint_node(state: AgentState) -> AgentState:
    print(f"\n⏸️  HUMAN CHECKPOINT: Waiting for user decision...")
    # In LangGraph, this node pauses execution
    # The FastAPI layer handles getting user input
    # and sets human_decision to "proceed" or "refine"
    return state

# ─────────────────────────────────────────────
# 8. NODE 6 — SYNTHESIZER
# Combines SQL + RAG results into one clean answer
# ─────────────────────────────────────────────
def synthesizer_node(state: AgentState) -> AgentState:
    print(f"\n✍️  SYNTHESIZER: Building final answer...")

    question    = state["question"]
    sql_result  = state.get("sql_result")
    rag_result  = state.get("rag_result")
    confidence  = state.get("confidence", {})

    # Build context for the LLM to synthesize
    context_parts = []

    if sql_result and sql_result.get("success") and sql_result.get("row_count", 0) > 0:
        # Limit to first 10 rows to keep context small
        rows = sql_result["results"][:10]
        context_parts.append(f"DATABASE RESULTS ({sql_result['row_count']} total rows):\n{json.dumps(rows, indent=2)}")

    if rag_result and rag_result.get("count", 0) > 0:
        docs = [item["document"] for item in rag_result["matched"]]
        context_parts.append(f"RELEVANT POLICY DOCUMENTS:\n" + "\n".join(f"- {d}" for d in docs))

    if not context_parts:
        context = "No relevant data or documents were found."
    else:
        context = "\n\n".join(context_parts)

    # Ask LLM to write a clean human-readable answer
    synthesis_prompt = f"""
You are a helpful assistant for TrinityRail, a North American railcar company.

Answer the user's question using ONLY the context provided below.
Be concise, clear, and professional.
Do not make up information beyond what is in the context.

Context:
{context}

User Question: {question}

Write a clear, direct answer in 2-4 sentences:
"""
    response = llm.invoke([HumanMessage(content=synthesis_prompt)])
    answer = response.content.strip()

    # --- Generate Follow-Up Suggestions ---
    followup_prompt = f"""
The user asked: "{question}"
The answer was: "{answer}"

Suggest exactly 2 short follow-up questions they might ask next.
Keep them specific to railcar operations.
Return ONLY a JSON array of 2 strings. Example: ["question 1", "question 2"]
No explanation. Just the JSON array.
"""
    followup_response = llm.invoke([HumanMessage(content=followup_prompt)])
    try:
        follow_ups = json.loads(followup_response.content.strip())
    except:
        follow_ups = [
            "Which region has the most idle railcars?",
            "Which cars are overdue for inspection?"
        ]

    print(f"   → Answer generated. Confidence: {confidence.get('level', 'N/A')}")

    return {**state, "final_answer": answer, "follow_ups": follow_ups}

# ─────────────────────────────────────────────
# 9. CONDITIONAL EDGE FUNCTIONS
# These decide which node to go to next
# ─────────────────────────────────────────────

def route_decision(state: AgentState) -> str:
    """After Router: which agent to call?"""
    route = state.get("route", "both")
    if route == "sql":
        return "sql_only"
    elif route == "rag":
        return "rag_only"
    else:
        return "both"

def after_sql_decision(state: AgentState) -> str:
    """After SQL agent (when route was sql only): go to confidence."""
    return "confidence"

def after_rag_decision(state: AgentState) -> str:
    """After RAG agent (when route was rag only): go to confidence."""
    return "confidence"

def checkpoint_decision(state: AgentState) -> str:
    """After confidence check: pause for human or go straight to synthesizer?"""
    if state.get("awaiting_human"):
        return "needs_human"
    return "skip_human"

def human_decision(state: AgentState) -> str:
    """After human checkpoint: proceed to answer or loop back to router?"""
    decision = state.get("human_decision", "proceed")
    if decision == "refine":
        return "loop_back"
    return "proceed"

# ─────────────────────────────────────────────
# 10. BUILD THE GRAPH
# Wire all nodes and edges together
# ─────────────────────────────────────────────

def build_graph():
    graph = StateGraph(AgentState)

    # Add all nodes
    graph.add_node("router",           router_node)
    graph.add_node("sql_agent",        sql_agent_node)
    graph.add_node("rag_agent",        rag_agent_node)
    graph.add_node("confidence",       confidence_node)
    graph.add_node("human_checkpoint", human_checkpoint_node)
    graph.add_node("synthesizer",      synthesizer_node)

    # Entry point
    graph.set_entry_point("router")

    # Conditional edge after router → sql, rag, or both
    graph.add_conditional_edges(
        "router",
        route_decision,
        {
            "sql_only" : "sql_agent",   # goes to SQL agent only
            "rag_only" : "rag_agent",   # goes to RAG agent only
            "both"     : "sql_agent"    # starts with SQL, then RAG
        }
    )

    # When route is "both" — SQL runs first, then RAG
    graph.add_edge("sql_agent", "rag_agent")

    # When route is "sql only" — SQL goes straight to confidence
    # This is handled by the conditional edge mapping above
    # but we add a direct edge for the "both" path
    graph.add_edge("rag_agent", "confidence")

    # Conditional edge after confidence → human checkpoint or synthesizer
    graph.add_conditional_edges(
        "confidence",
        checkpoint_decision,
        {
            "needs_human" : "human_checkpoint",
            "skip_human"  : "synthesizer"
        }
    )

    # Conditional edge after human checkpoint → proceed or loop back
    graph.add_conditional_edges(
        "human_checkpoint",
        human_decision,
        {
            "proceed"   : "synthesizer",
            "loop_back" : "router"       # loops back! user refined the question
        }
    )

    # Final edge — synthesizer is always the last step
    graph.add_edge("synthesizer", END)

    # MemorySaver enables human-in-the-loop pause/resume
    memory = MemorySaver()
    return graph.compile(
        checkpointer=memory,
        interrupt_before=["human_checkpoint"]  # pause HERE and wait
    )

# Build it once when imported
trinity_graph = build_graph()

# ─────────────────────────────────────────────
# 11. HELPER FUNCTION — called by FastAPI
# ─────────────────────────────────────────────

def ask_agent(question: str, thread_id: str = "default") -> dict:
    """
    Runs the full agent graph for a question.
    Returns the final structured response.
    """
    config = {"configurable": {"thread_id": thread_id}}

    initial_state = {
        "question"       : question,
        "route"          : None,
        "sql_query"      : None,
        "sql_result"     : None,
        "rag_result"     : None,
        "confidence"     : None,
        "checkpoint"     : None,
        "awaiting_human" : False,
        "human_decision" : None,
        "final_answer"   : None,
        "follow_ups"     : []
    }

    # Run the graph
    result = trinity_graph.invoke(initial_state, config=config)

    # If human checkpoint was triggered, graph paused here
    if result.get("awaiting_human"):
        return {
            "status"           : "awaiting_human",
            "checkpoint_message": result["checkpoint"]["message"],
            "thread_id"        : thread_id
        }

    return {
        "status"     : "complete",
        "answer"     : result.get("final_answer", "I could not generate an answer."),
        "confidence" : result.get("confidence", {}).get("level", "Unknown"),
        "follow_ups" : result.get("follow_ups", []),
        "sql_used"   : result.get("sql_query"),
        "thread_id"  : thread_id
    }

def resume_agent(thread_id: str, decision: str) -> dict:
    """
    Resumes the graph after human checkpoint.
    decision: "proceed" or "refine"
    """
    config = {"configurable": {"thread_id": thread_id}}

    # Update state with human decision and resume
    trinity_graph.update_state(
        config,
        {"human_decision": decision, "awaiting_human": False}
    )

    result = trinity_graph.invoke(None, config=config)

    return {
        "status"     : "complete",
        "answer"     : result.get("final_answer", "I could not generate an answer."),
        "confidence" : result.get("confidence", {}).get("level", "Unknown"),
        "follow_ups" : result.get("follow_ups", []),
        "sql_used"   : result.get("sql_query"),
        "thread_id"  : thread_id
    }